### ISSUE TITLE
Traceback error on KeyboardInterrupt

### ISSUE THREAD

**Issue by frawst** [EclectickMedia/PingStats#37]
Traceback when exiting from command:
```
-a google.ca
```
```
Traceback (most recent call last):
  File "PingStats.py", line 181, in <module>
    for return_tuple in ping(parsed.address):
  File "PingStats.py", line 83, in ping
    time.sleep(0.22)
KeyboardInterrupt
```
Interrupt acts as expected.

Traceback when exiting from command:
```
-a google.ca -s
```
```
Traceback (most recent call last):
  File "PingStats.py", line 164, in <module>
    plot.animate()
  File "A:\Maya\Projects\PingStats\Plot.py", line 112, in animate
    return self.show_plot()
  File "A:\Maya\Projects\PingStats\Plot.py", line 89, in show_plot
    plt.show()
  File "C:\Python34\lib\site-packages\matplotlib\pyplot.py", line 252, in show
    return _show(*args, **kw)
  File "C:\Python34\lib\site-packages\matplotlib\backend_bases.py", line 192, in
 __call__
    self.mainloop()
  File "C:\Python34\lib\site-packages\matplotlib\backends\backend_tkagg.py", lin
e 74, in mainloop
    Tk.mainloop()
  File "C:\Python34\lib\tkinter\__init__.py", line 403, in mainloop
    _default_root.tk.mainloop(n)
KeyboardInterrupt
```
Simply throws traceback and continues to run, will not accept further input. Requires force-quit.

**Comment by EclectickMedia** [comment]
Try throwing an extra two keyboard interrupts.

This is a bug introduced in `V2.0.0`, and is lying around somewhere in `matplotlib` callback functions.

**Comment by frawst** [comment]
Ah yes, so the matplotlib window actually crashes when I throw the interrupt. However, the script itself will not accept any further attempts to interrupt. It just keeps running. I threw interrupts for about 300 pings to no avail. Not sure if this helps.

**Comment by EclectickMedia** [comment]
Hmm... That's slightly different behavior than my internal implementation. 

Can you attach version info? Especially `git log --oneline -n 1`. And, if they are available, the output of `sudo python3 tests.py`.  You may need to check the Readme to run the tests. The tests will output version info on their own. 

If you need to update the code available on your machine to get the tests, run `git pull`.

**Comment by frawst** [comment]
```
A:\Maya\Projects\PingStats>git log --oneline -n 1
04b6960 Updated call to pythonping.single_ping to reflect repo commit bf2eac4
```

```python
A:\Maya\Projects\PingStats>py pythonping/tests.py
EEE
======================================================================
ERROR: test_instantiation (__main__.MyStats_test)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "pythonping/tests.py", line 26, in test_instantiation
    self.assertIsInstance(ping.MyStats(), ping.MyStats, msg="Failed MyStats inst
antiation!")
AttributeError: 'module' object has no attribute 'MyStats'

======================================================================
ERROR: test_fail_arraypack (__main__.checksum_test)
Confirm that checksum properly throws errors during runtime by giving it a strin
g and int object i
----------------------------------------------------------------------
Traceback (most recent call last):
  File "pythonping/tests.py", line 35, in test_fail_arraypack
    x = ping.checksum('test string')
AttributeError: 'module' object has no attribute 'checksum'

======================================================================
ERROR: test_succeed_arraypack (__main__.checksum_test)
Confirm that the checksum returns predictable output.
----------------------------------------------------------------------
Traceback (most recent call last):
  File "pythonping/tests.py", line 41, in test_succeed_arraypack
    self.assertEqual(ping.checksum(b'12345'), 26265)
AttributeError: 'module' object has no attribute 'checksum'

----------------------------------------------------------------------
Ran 3 tests in 0.002s

FAILED (errors=3)
```

**Comment by EclectickMedia** [comment]
Run `git pull` in the PingStats directory. It will update the software.

These are also the commits for python-ping, not my code. Those tests are dead.

After you've pulled commit cfccf2a96a4c0a3b56978f0507e9a18a1bdb2394 try running the tests within the PingStats code.

**Comment by frawst** [comment]
```
os.name: nt
platform.system: Windows
platform.release: 7
PingStats version: 2.0.02
Python version (via sys.version): 3.4.3 (v3.4.3:9b73f1c3e601, Feb 24 2015, 22:44
:40) [MSC v.1600 64 bit (AMD64)]


.Falsifying example: test_build_files(self=<__main__.TestCore testMethod=test_bu
ild_files>, path='.', name='*')
EC:\Python34\lib\site-packages\hypothesis\internal\conjecture\engine.py:86: Reso
urceWarning: unclosed <socket.socket fd=748, family=AddressFamily.AF_INET, type=
SocketKind.SOCK_RAW, proto=1>
  raise e
C:\Python34\lib\site-packages\hypothesis\internal\conjecture\engine.py:86: Resou
rceWarning: unclosed <socket.socket fd=272, family=AddressFamily.AF_INET, type=S
ocketKind.SOCK_RAW, proto=1>
  raise e
C:\Python34\lib\site-packages\hypothesis\internal\conjecture\engine.py:86: Resou
rceWarning: unclosed <socket.socket fd=744, family=AddressFamily.AF_INET, type=S
ocketKind.SOCK_RAW, proto=1>
  raise e
Request timed out.
Request timed out.
Request timed out.
Request timed out.
Request timed out.
Request timed out.
Request timed out.
Request timed out.
Request timed out.
Falsifying example: test_failed_connections(self=<__main__.TestCore testMethod=t
est_failed_connections>, address='\x85')
EC:\Python34\lib\unittest\case.py:605: ResourceWarning: unclosed <socket.socket
fd=744, family=AddressFamily.AF_INET, type=SocketKind.SOCK_RAW, proto=1>
  outcome.errors.clear()
.
======================================================================
ERROR: test_build_files (__main__.TestCore)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "tests.py", line 17, in test_build_files
    def test_build_files(self, path, name):
  File "C:\Python34\lib\site-packages\hypothesis\core.py", line 524, in wrapped_
test
    print_example=True, is_final=True
  File "C:\Python34\lib\site-packages\hypothesis\executors.py", line 58, in defa
ult_new_style_executor
    return function(data)
  File "C:\Python34\lib\site-packages\hypothesis\core.py", line 111, in run
    return test(*args, **kwargs)
  File "tests.py", line 19, in test_build_files
    test_file = PingStats.buildfile(path, name)
  File "A:\Maya\Projects\PingStats\PingStats.py", line 69, in buildfile
    return open(path + name, 'a+')
OSError: [Errno 22] Invalid argument: '.*.csv'

======================================================================
ERROR: test_failed_connections (__main__.TestCore)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Python34\lib\encodings\idna.py", line 181, in encode
    result.extend(ToASCII(label))
  File "C:\Python34\lib\encodings\idna.py", line 76, in ToASCII
    label = nameprep(label)
  File "C:\Python34\lib\encodings\idna.py", line 38, in nameprep
    raise UnicodeError("Invalid character %r" % c)
UnicodeError: Invalid character '\x85'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "tests.py", line 48, in test_failed_connections
    def test_failed_connections(self, address):
  File "C:\Python34\lib\site-packages\hypothesis\core.py", line 524, in wrapped_
test
    print_example=True, is_final=True
  File "C:\Python34\lib\site-packages\hypothesis\executors.py", line 58, in defa
ult_new_style_executor
    return function(data)
  File "C:\Python34\lib\site-packages\hypothesis\core.py", line 111, in run
    return test(*args, **kwargs)
  File "tests.py", line 49, in test_failed_connections
    self.assertEqual(PingStats.ping(address, verbose=False).__next__()[1],
  File "A:\Maya\Projects\PingStats\PingStats.py", line 92, in ping
    verbose=verbose)[0],
  File "A:\Maya\Projects\PingStats\pythonping\ping.py", line 140, in single_ping

    verbose)
  File "A:\Maya\Projects\PingStats\pythonping\ping.py", line 241, in _send
    mySocket.sendto(packet, (destIP, 1))  # Port number is irrelevant
UnicodeError: encoding with 'idna' codec failed (UnicodeError: Invalid character
 '\x85')

----------------------------------------------------------------------
Ran 4 tests in 69.367s

FAILED (errors=2)
```

**Comment by EclectickMedia** [comment]
Aside from the namespace issues with broken characters that window's doesnt allow failing, it looks like that ran about according to plan.

I'm working on tests for the Plotting feature right now, will update with more information as I have it.

**Comment by frawst** [comment]
```
Mon Dec  5 20:23:47 2016
os.name: nt
platform.system: Windows
platform.release: 7
PingStats version: 2.0.02
Python version (via sys.version): 3.4.3 (v3.4.3:9b73f1c3e601, Feb 24 2015, 22:44
:40) [MSC v.1600 64 bit (AMD64)]
stdout:
b'3e75937 Forced buffered output of unittests\n'
stderr:
b''


.F
Stdout:
Falsifying example: test_instantiate_catch_null_byte_title_string(self=<__main__
.BasePlot_test testMethod=test_instantiate_catch_null_byte_title_string>, data='
\x00')
...........E
Stdout:
Falsifying example: test_active_connections(self=<__main__.TestCore testMethod=t
est_active_connections>, address='127.0.0.1')
E
Stdout:
Falsifying example: test_build_files(self=<__main__.TestCore testMethod=test_bui
ld_files>, path='.', name='*')
E
Stdout:
Falsifying example: test_failed_connections(self=<__main__.TestCore testMethod=t
est_failed_connections>, address='')
.
======================================================================
ERROR: test_active_connections (__main__.TestCore)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "tests.py", line 42, in test_active_connections
    def test_active_connections(self, address):
  File "C:\Python34\lib\site-packages\hypothesis\core.py", line 524, in wrapped_
test
    print_example=True, is_final=True
  File "C:\Python34\lib\site-packages\hypothesis\executors.py", line 58, in defa
ult_new_style_executor
    return function(data)
  File "C:\Python34\lib\site-packages\hypothesis\core.py", line 111, in run
    return test(*args, **kwargs)
  File "tests.py", line 45, in test_active_connections
    verbose=False).__next__()[1],
  File "A:\Maya\Projects\PingStats\PingStats.py", line 92, in ping
    verbose=verbose)[0],
  File "A:\Maya\Projects\PingStats\pythonping\ping.py", line 128, in single_ping

    socket.getprotobyname("icmp"))
  File "C:\Python34\lib\socket.py", line 126, in __init__
    _socket.socket.__init__(self, family, type, proto, fileno)
OSError: [WinError 10013] An attempt was made to access a socket in a way forbid
den by its access permissions

Stdout:
Falsifying example: test_active_connections(self=<__main__.TestCore testMethod=t
est_active_connections>, address='127.0.0.1')

======================================================================
ERROR: test_build_files (__main__.TestCore)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "tests.py", line 21, in test_build_files
    def test_build_files(self, path, name):
  File "C:\Python34\lib\site-packages\hypothesis\core.py", line 524, in wrapped_
test
    print_example=True, is_final=True
  File "C:\Python34\lib\site-packages\hypothesis\executors.py", line 58, in defa
ult_new_style_executor
    return function(data)
  File "C:\Python34\lib\site-packages\hypothesis\core.py", line 111, in run
    return test(*args, **kwargs)
  File "tests.py", line 23, in test_build_files
    test_file = PingStats.buildfile(path, name)
  File "A:\Maya\Projects\PingStats\PingStats.py", line 69, in buildfile
    return open(path + name, 'a+')
OSError: [Errno 22] Invalid argument: '.*.csv'

Stdout:
Falsifying example: test_build_files(self=<__main__.TestCore testMethod=test_bui
ld_files>, path='.', name='*')

======================================================================
ERROR: test_failed_connections (__main__.TestCore)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "tests.py", line 52, in test_failed_connections
    def test_failed_connections(self, address):
  File "C:\Python34\lib\site-packages\hypothesis\core.py", line 524, in wrapped_
test
    print_example=True, is_final=True
  File "C:\Python34\lib\site-packages\hypothesis\executors.py", line 58, in defa
ult_new_style_executor
    return function(data)
  File "C:\Python34\lib\site-packages\hypothesis\core.py", line 111, in run
    return test(*args, **kwargs)
  File "tests.py", line 53, in test_failed_connections
    self.assertEqual(PingStats.ping(address, verbose=False).__next__()[1],
  File "A:\Maya\Projects\PingStats\PingStats.py", line 92, in ping
    verbose=verbose)[0],
  File "A:\Maya\Projects\PingStats\pythonping\ping.py", line 128, in single_ping

    socket.getprotobyname("icmp"))
  File "C:\Python34\lib\socket.py", line 126, in __init__
    _socket.socket.__init__(self, family, type, proto, fileno)
OSError: [WinError 10013] An attempt was made to access a socket in a way forbid
den by its access permissions

Stdout:
Falsifying example: test_failed_connections(self=<__main__.TestCore testMethod=t
est_failed_connections>, address='')

======================================================================
FAIL: test_instantiate_catch_null_byte_title_string (__main__.BasePlot_test)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "tests.py", line 130, in test_instantiate_catch_null_byte_title_string
    def test_instantiate_catch_null_byte_title_string(self, data):
  File "C:\Python34\lib\site-packages\hypothesis\core.py", line 524, in wrapped_
test
    print_example=True, is_final=True
  File "C:\Python34\lib\site-packages\hypothesis\executors.py", line 58, in defa
ult_new_style_executor
    return function(data)
  File "C:\Python34\lib\site-packages\hypothesis\core.py", line 111, in run
    return test(*args, **kwargs)
  File "tests.py", line 134, in test_instantiate_catch_null_byte_title_string
    plot()
AssertionError: TypeError not raised

Stdout:
Falsifying example: test_instantiate_catch_null_byte_title_string(self=<__main__
.BasePlot_test testMethod=test_instantiate_catch_null_byte_title_string>, data='
\x00')

----------------------------------------------------------------------
Ran 17 tests in 2.795s

FAILED (failures=1, errors=3)
```

**Comment by EclectickMedia** [comment]
The software needs to be run with administrator (read sudo) permissions.

Open the command line with administrator by right clicking the CMD executable and running as administrator.

**Comment by frawst** [comment]
```
Mon Dec  5 21:47:17 2016
os.name: nt
platform.system: Windows
platform.release: 7
PingStats version: 2.0.02
Python version (via sys.version): 3.4.3 (v3.4.3:9b73f1c3e601, Feb 24 2015, 22:44
:40) [MSC v.1600 64 bit (AMD64)]
stdout:
b'3e75937 Forced buffered output of unittests\n'
stderr:
b''


.F
Stdout:
Falsifying example: test_instantiate_catch_null_byte_title_string(self=<__main__
.BasePlot_test testMethod=test_instantiate_catch_null_byte_title_string>, data='
\x00')
............E
Stdout:
Falsifying example: test_build_files(self=<__main__.TestCore testMethod=test_bui
ld_files>, path='.', name='*')
E
Stdout:
Request timed out.
Request timed out.
Request timed out.
Request timed out.
Request timed out.
Request timed out.
Request timed out.
Request timed out.
Request timed out.
Falsifying example: test_failed_connections(self=<__main__.TestCore testMethod=t
est_failed_connections>, address='\x85')

Stderr:
C:\Python34\lib\site-packages\hypothesis\internal\conjecture\engine.py:86: Resou
rceWarning: unclosed <socket.socket fd=736, family=AddressFamily.AF_INET, type=S
ocketKind.SOCK_RAW, proto=1>
  raise e
C:\Python34\lib\unittest\case.py:605: ResourceWarning: unclosed <socket.socket f
d=736, family=AddressFamily.AF_INET, type=SocketKind.SOCK_RAW, proto=1>
  outcome.errors.clear()
.
======================================================================
ERROR: test_build_files (__main__.TestCore)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "tests.py", line 21, in test_build_files
    def test_build_files(self, path, name):
  File "C:\Python34\lib\site-packages\hypothesis\core.py", line 524, in wrapped_
test
    print_example=True, is_final=True
  File "C:\Python34\lib\site-packages\hypothesis\executors.py", line 58, in defa
ult_new_style_executor
    return function(data)
  File "C:\Python34\lib\site-packages\hypothesis\core.py", line 111, in run
    return test(*args, **kwargs)
  File "tests.py", line 23, in test_build_files
    test_file = PingStats.buildfile(path, name)
  File "A:\Maya\Projects\PingStats\PingStats.py", line 69, in buildfile
    return open(path + name, 'a+')
OSError: [Errno 22] Invalid argument: '.*.csv'

Stdout:
Falsifying example: test_build_files(self=<__main__.TestCore testMethod=test_bui
ld_files>, path='.', name='*')

======================================================================
ERROR: test_failed_connections (__main__.TestCore)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Python34\lib\encodings\idna.py", line 181, in encode
    result.extend(ToASCII(label))
  File "C:\Python34\lib\encodings\idna.py", line 76, in ToASCII
    label = nameprep(label)
  File "C:\Python34\lib\encodings\idna.py", line 38, in nameprep
    raise UnicodeError("Invalid character %r" % c)
UnicodeError: Invalid character '\x85'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "tests.py", line 52, in test_failed_connections
    def test_failed_connections(self, address):
  File "C:\Python34\lib\site-packages\hypothesis\core.py", line 524, in wrapped_
test
    print_example=True, is_final=True
  File "C:\Python34\lib\site-packages\hypothesis\executors.py", line 58, in defa
ult_new_style_executor
    return function(data)
  File "C:\Python34\lib\site-packages\hypothesis\core.py", line 111, in run
    return test(*args, **kwargs)
  File "tests.py", line 53, in test_failed_connections
    self.assertEqual(PingStats.ping(address, verbose=False).__next__()[1],
  File "A:\Maya\Projects\PingStats\PingStats.py", line 92, in ping
    verbose=verbose)[0],
  File "A:\Maya\Projects\PingStats\pythonping\ping.py", line 140, in single_ping

    verbose)
  File "A:\Maya\Projects\PingStats\pythonping\ping.py", line 241, in _send
    mySocket.sendto(packet, (destIP, 1))  # Port number is irrelevant
UnicodeError: encoding with 'idna' codec failed (UnicodeError: Invalid character
 '\x85')

Stdout:
Request timed out.
Request timed out.
Request timed out.
Request timed out.
Request timed out.
Request timed out.
Request timed out.
Request timed out.
Request timed out.
Falsifying example: test_failed_connections(self=<__main__.TestCore testMethod=t
est_failed_connections>, address='\x85')

Stderr:
C:\Python34\lib\site-packages\hypothesis\internal\conjecture\engine.py:86: Resou
rceWarning: unclosed <socket.socket fd=736, family=AddressFamily.AF_INET, type=S
ocketKind.SOCK_RAW, proto=1>
  raise e

======================================================================
FAIL: test_instantiate_catch_null_byte_title_string (__main__.BasePlot_test)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "tests.py", line 130, in test_instantiate_catch_null_byte_title_string
    def test_instantiate_catch_null_byte_title_string(self, data):
  File "C:\Python34\lib\site-packages\hypothesis\core.py", line 524, in wrapped_
test
    print_example=True, is_final=True
  File "C:\Python34\lib\site-packages\hypothesis\executors.py", line 58, in defa
ult_new_style_executor
    return function(data)
  File "C:\Python34\lib\site-packages\hypothesis\core.py", line 111, in run
    return test(*args, **kwargs)
  File "tests.py", line 134, in test_instantiate_catch_null_byte_title_string
    plot()
AssertionError: TypeError not raised

Stdout:
Falsifying example: test_instantiate_catch_null_byte_title_string(self=<__main__
.BasePlot_test testMethod=test_instantiate_catch_null_byte_title_string>, data='
\x00')

----------------------------------------------------------------------
Ran 17 tests in 64.506s

FAILED (failures=1, errors=2)
```

**Comment by EclectickMedia** [comment]
Im actually going to close this issue, and open it under another thread.
