### ISSUE TITLE
Core.buildfile is not catching null byte errors on windows

### ISSUE THREAD

**Issue by EclectickMedia** [EclectickMedia/PingStats#49]
Tests printout:

```
PingStats>python tests.py -v
Sat Dec 10 23:48:09 2016
os.name: nt
platform.system: Windows
platform.release: 10
PingStats version: 2.1
Python version (via sys.version): 3.5.2 (v3.5.2:4def2a2901a5, Jun 25 2016, 22:01:18) [MSC v.1900 32 bit (Intel)]
stdout:
b'c1faa63 Updated version tag to V2.1\n'
stderr:
b''


test_instantiate_catch_invalid_title_string (__main__.BasePlot_test) ... ok
test_instantiate_catch_null_byte_title_string (__main__.BasePlot_test) ... ok
test_instantiate_nofile (__main__.BasePlot_test) ... ok
test_appendx_data_addition (__main__.PlotTable_test) ... ok
test_appendx_flood (__main__.PlotTable_test) ... ok
test_appendx_invalid_data_catch (__main__.PlotTable_test) ... ok
test_appendy_data_addition (__main__.PlotTable_test) ... ok
test_appendy_flood (__main__.PlotTable_test) ... ok
test_appendy_invalid_data_catch (__main__.PlotTable_test) ... ok
test_instantiate (__main__.PlotTable_test) ... ok
test_instantiate_catch_invalid_data (__main__.PlotTable_test) ... ok
test_instantiate_catch_zero_length (__main__.PlotTable_test) ... ok
test_instantiate_with_length_as_int (__main__.PlotTable_test) ... ok
test_active_connections (__main__.TestCore) ... ok
test_build_files (__main__.TestCore) ... ERROR

Stdout:
Failed to open '.csv', defaulting to 'PingStatsLog.csv'.
TestCore.test_build_files caught OS non legal file path: .
Failed to open '..csv', defaulting to 'PingStatsLog.csv'.
TestCore.test_build_files caught OS non legal file path: .
Failed to open '..csv', defaulting to 'PingStatsLog.csv'.
TestCore.test_build_files caught OS non legal file path: .
Failed to open '..csv', defaulting to 'PingStatsLog.csv'.
TestCore.test_build_files caught OS non legal file path: .
Failed to open '..csv', defaulting to 'PingStatsLog.csv'.
TestCore.test_build_files caught OS non legal file path: .
Failed to open '..csv', defaulting to 'PingStatsLog.csv'.
TestCore.test_build_files caught OS non legal file path: .
Failed to open '..csv', defaulting to 'PingStatsLog.csv'.
TestCore.test_build_files caught OS non legal file path: .
Failed to open '..csv', defaulting to 'PingStatsLog.csv'.
TestCore.test_build_files caught OS non legal file path: .
Failed to open '..csv', defaulting to 'PingStatsLog.csv'.
TestCore.test_build_files caught OS non legal file path: .
Falsifying example: test_build_files(self=<__main__.TestCore testMethod=test_build_files>, path='.', name='\x00')
test_build_files_fail_on_invalid_character (__main__.TestCore) ... ok
test_failed_connections (__main__.TestCore) ... ok
test_write_csv_data (__main__.TestCore) ... ok

======================================================================
ERROR: test_build_files (__main__.TestCore)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "tests.py", line 22, in test_build_files
    def test_build_files(self, path, name):
  File "D:\lib\site-packages\hypothesis\core.py", line 524, in wrapped_test
    print_example=True, is_final=True
  File "D:\lib\site-packages\hypothesis\executors.py", line 58, in default_new_style_executor
    return function(data)
  File "D:\lib\site-packages\hypothesis\core.py", line 111, in run
    return test(*args, **kwargs)
  File "tests.py", line 24, in test_build_files
    test_file = c.buildfile(path, name)
  File "C:\Users\Zack\PingStats\core.py", line 57, in buildfile
    return open(path + name, 'a+')
ValueError: embedded null character

Stdout:
Failed to open '.csv', defaulting to 'PingStatsLog.csv'.
TestCore.test_build_files caught OS non legal file path: .
Failed to open '..csv', defaulting to 'PingStatsLog.csv'.
TestCore.test_build_files caught OS non legal file path: .
Failed to open '..csv', defaulting to 'PingStatsLog.csv'.
TestCore.test_build_files caught OS non legal file path: .
Failed to open '..csv', defaulting to 'PingStatsLog.csv'.
TestCore.test_build_files caught OS non legal file path: .
Failed to open '..csv', defaulting to 'PingStatsLog.csv'.
TestCore.test_build_files caught OS non legal file path: .
Failed to open '..csv', defaulting to 'PingStatsLog.csv'.
TestCore.test_build_files caught OS non legal file path: .
Failed to open '..csv', defaulting to 'PingStatsLog.csv'.
TestCore.test_build_files caught OS non legal file path: .
Failed to open '..csv', defaulting to 'PingStatsLog.csv'.
TestCore.test_build_files caught OS non legal file path: .
Failed to open '..csv', defaulting to 'PingStatsLog.csv'.
TestCore.test_build_files caught OS non legal file path: .
Falsifying example: test_build_files(self=<__main__.TestCore testMethod=test_build_files>, path='.', name='\x00')

----------------------------------------------------------------------
Ran 18 tests in 2.713s

FAILED (errors=1)```

**Comment by EclectickMedia** [comment]
After pull 5d26c1047ad16d977770d046a509039b9eac40fe, the tests produce the same output:

```
python tests.py -v
Sun Dec 11 00:52:47 2016
os.name: nt
platform.system: Windows
platform.release: 10
PingStats version: 2.1
Python version (via sys.version): 3.5.2 (v3.5.2:4def2a2901a5, Jun 25 2016, 22:01:18) [MSC v.1900 32 bit (Intel)]
stdout:
b'7b23137 Updated version string\n'
stderr:
b''


test_instantiate_catch_invalid_title_string (__main__.BasePlot_test) ... ok
test_instantiate_catch_null_byte_title_string (__main__.BasePlot_test) ... ok
test_instantiate_nofile (__main__.BasePlot_test) ... ok
test_appendx_data_addition (__main__.PlotTable_test) ... ok
test_appendx_flood (__main__.PlotTable_test) ... ok
test_appendx_invalid_data_catch (__main__.PlotTable_test) ... ok
test_appendy_data_addition (__main__.PlotTable_test) ... ok
test_appendy_flood (__main__.PlotTable_test) ... ok
test_appendy_invalid_data_catch (__main__.PlotTable_test) ... ok
test_instantiate (__main__.PlotTable_test) ... ok
test_instantiate_catch_invalid_data (__main__.PlotTable_test) ... ok
test_instantiate_catch_zero_length (__main__.PlotTable_test) ... ok
test_instantiate_with_length_as_int (__main__.PlotTable_test) ... ok
test_active_connections (__main__.TestCore) ... ok
test_build_files (__main__.TestCore) ... ERROR

Stdout:
Failed to open '.csv', defaulting to 'PingStatsLog.csv'.
Failed to open '..csv', defaulting to 'PingStatsLog.csv'.
TestCore.test_build_files caught OS non legal file path: .
Failed to open '..csv', defaulting to 'PingStatsLog.csv'.
TestCore.test_build_files caught OS non legal file path: .
Failed to open '..csv', defaulting to 'PingStatsLog.csv'.
TestCore.test_build_files caught OS non legal file path: .
Failed to open '..csv', defaulting to 'PingStatsLog.csv'.
TestCore.test_build_files caught OS non legal file path: .
Failed to open '..csv', defaulting to 'PingStatsLog.csv'.
TestCore.test_build_files caught OS non legal file path: .
Failed to open '..csv', defaulting to 'PingStatsLog.csv'.
TestCore.test_build_files caught OS non legal file path: .
Failed to open '..csv', defaulting to 'PingStatsLog.csv'.
TestCore.test_build_files caught OS non legal file path: .
Failed to open '..csv', defaulting to 'PingStatsLog.csv'.
TestCore.test_build_files caught OS non legal file path: .
Falsifying example: test_build_files(self=<__main__.TestCore testMethod=test_build_files>, path='.', name='\x00')
test_build_files_fail_on_invalid_character (__main__.TestCore) ... ok
test_failed_connections (__main__.TestCore) ... ok
test_write_csv_data (__main__.TestCore) ... ok

======================================================================
ERROR: test_build_files (__main__.TestCore)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "tests.py", line 22, in test_build_files
    def test_build_files(self, path, name):
  File "D:\lib\site-packages\hypothesis\core.py", line 524, in wrapped_test
    print_example=True, is_final=True
  File "D:\lib\site-packages\hypothesis\executors.py", line 58, in default_new_style_executor
    return function(data)
  File "D:\lib\site-packages\hypothesis\core.py", line 111, in run
    return test(*args, **kwargs)
  File "tests.py", line 24, in test_build_files
    test_file = c.Core.buildfile(path, name)
  File "C:\Users\Zack\PingStats\core.py", line 56, in buildfile
    return open(path + name, 'a+')
ValueError: embedded null character

Stdout:
Failed to open '.csv', defaulting to 'PingStatsLog.csv'.
Failed to open '..csv', defaulting to 'PingStatsLog.csv'.
TestCore.test_build_files caught OS non legal file path: .
Failed to open '..csv', defaulting to 'PingStatsLog.csv'.
TestCore.test_build_files caught OS non legal file path: .
Failed to open '..csv', defaulting to 'PingStatsLog.csv'.
TestCore.test_build_files caught OS non legal file path: .
Failed to open '..csv', defaulting to 'PingStatsLog.csv'.
TestCore.test_build_files caught OS non legal file path: .
Failed to open '..csv', defaulting to 'PingStatsLog.csv'.
TestCore.test_build_files caught OS non legal file path: .
Failed to open '..csv', defaulting to 'PingStatsLog.csv'.
TestCore.test_build_files caught OS non legal file path: .
Failed to open '..csv', defaulting to 'PingStatsLog.csv'.
TestCore.test_build_files caught OS non legal file path: .
Failed to open '..csv', defaulting to 'PingStatsLog.csv'.
TestCore.test_build_files caught OS non legal file path: .
Falsifying example: test_build_files(self=<__main__.TestCore testMethod=test_build_files>, path='.', name='\x00')

----------------------------------------------------------------------
Ran 18 tests in 2.621s

FAILED (errors=1)
```

**Comment by EclectickMedia** [comment]
Updated tests for dc8d6c4f41d585d0b2308775a8d2385250ba5617:

```
python tests.py -v
Sun Dec 11 01:42:32 2016
os.name: nt
platform.system: Windows
platform.release: 10
PingStats version: 2.1
Python version (via sys.version): 3.5.2 (v3.5.2:4def2a2901a5, Jun 25 2016, 22:01:18) [MSC v.1900 32 bit (Intel)]
stdout:
b'dc8d6c4 Added text validation function to core.\n'
stderr:
b''


test_instantiate_catch_invalid_title_string (__main__.BasePlot_test) ... ok
test_instantiate_catch_null_byte_title_string (__main__.BasePlot_test) ... ok
test_instantiate_nofile (__main__.BasePlot_test) ... ok
test_appendx_data_addition (__main__.PlotTable_test) ... ok
test_appendx_flood (__main__.PlotTable_test) ... ok
test_appendx_invalid_data_catch (__main__.PlotTable_test) ... ok
test_appendy_data_addition (__main__.PlotTable_test) ... ok
test_appendy_flood (__main__.PlotTable_test) ... ok
test_appendy_invalid_data_catch (__main__.PlotTable_test) ... ok
test_instantiate (__main__.PlotTable_test) ... ok
test_instantiate_catch_invalid_data (__main__.PlotTable_test) ... ok
test_instantiate_catch_zero_length (__main__.PlotTable_test) ... ok
test_instantiate_with_length_as_int (__main__.PlotTable_test) ... ok
test_active_connections (__main__.TestCore) ... ok
test_build_files (__main__.TestCore) ... ok
test_build_files_fail_on_invalid_character (__main__.TestCore) ... ok
test_complete_string_validation (__main__.TestCore) ... ok
test_fail_string_validation (__main__.TestCore) ... ok
test_failed_connections (__main__.TestCore) ... ok
test_init (__main__.TestCore) ... ok
test_write_csv_data (__main__.TestCore) ... ok

----------------------------------------------------------------------
Ran 21 tests in 2.786s

OK
```

It would seem that this commit fixes this issue. Will attach further runtime environments.

**Comment by EclectickMedia** [comment]
The bug was appearing on my MacOSx machine, but has been fixed by the closing commit.

```
$ sudo python3 tests.py -v
Sun Dec 11 01:45:00 2016
os.name: posix
platform.system: Darwin
platform.release: 16.1.0
PingStats version: 2.1
Python version (via sys.version): 3.5.1 (v3.5.1:37a07cee5969, Dec  5 2015, 21:12:44) 
[GCC 4.2.1 (Apple Inc. build 5666) (dot 3)]
stdout: 
b'dc8d6c4 Added text validation function to core.\n'
stderr:
b''


test_instantiate_catch_invalid_title_string (__main__.BasePlot_test) ... ok
test_instantiate_catch_null_byte_title_string (__main__.BasePlot_test) ... ok
test_instantiate_nofile (__main__.BasePlot_test) ... ok
test_appendx_data_addition (__main__.PlotTable_test) ... ok
test_appendx_flood (__main__.PlotTable_test) ... ok
test_appendx_invalid_data_catch (__main__.PlotTable_test) ... ok
test_appendy_data_addition (__main__.PlotTable_test) ... ok
test_appendy_flood (__main__.PlotTable_test) ... ok
test_appendy_invalid_data_catch (__main__.PlotTable_test) ... ok
test_instantiate (__main__.PlotTable_test) ... ok
test_instantiate_catch_invalid_data (__main__.PlotTable_test) ... ok
test_instantiate_catch_zero_length (__main__.PlotTable_test) ... ok
test_instantiate_with_length_as_int (__main__.PlotTable_test) ... ok
test_active_connections (__main__.TestCore) ... ok
test_build_files (__main__.TestCore) ... ok
test_build_files_fail_on_invalid_character (__main__.TestCore) ... ok
test_complete_string_validation (__main__.TestCore) ... ok
test_fail_string_validation (__main__.TestCore) ... ok
test_failed_connections (__main__.TestCore) ... ok
test_init (__main__.TestCore) ... ok
test_write_csv_data (__main__.TestCore) ... ok

----------------------------------------------------------------------
Ran 21 tests in 2.061s

OK```
