### ISSUE TITLE
Generating a plot from a file functionality needs testing.

### ISSUE THREAD

**Issue by EclectickMedia** [EclectickMedia/PingStats#50]
`V2.1` has not been tested with generating a plot in a very long time. Someone should try running the `-pf` and `-gi` flags from the command line, and attach the results/description of what happened.

These features havent been tested since at least b62dd9e085d38f97c99e818e6161b0056ddfaeed

**Comment by EclectickMedia** [comment]
Test output from commit 4c5ff389e141cc9ff417f755f5bca0acadfe8a39 using a file generated by running:

    sudo python3 main.py -a google.ca -n 'TEST'

Which generated a file containing:
```
2016-12-11 03:12:49.443601,19.02604103088379,3000,64,google.ca
2016-12-11 03:12:49.683340,11.538028717041016,3000,64,google.ca
2016-12-11 03:12:49.915306,13.104915618896484,3000,64,google.ca
2016-12-11 03:12:50.149782,11.404991149902344,3000,64,google.ca
2016-12-11 03:12:50.381887,9.19198989868164,3000,64,google.ca
2016-12-11 03:12:50.612521,10.856866836547852,3000,64,google.ca
2016-12-11 03:12:50.844817,7.416963577270508,3000,64,google.ca
2016-12-11 03:12:51.072867,13.05699348449707,3000,64,google.ca
2016-12-11 03:12:51.306430,11.984109878540039,3000,64,google.ca
2016-12-11 03:12:51.539148,10.982036590576172,3000,64,google.ca
2016-12-11 03:12:51.771172,18.533945083618164,3000,64,google.ca
2016-12-11 03:12:52.011230,10.988950729370117,3000,64,google.ca
2016-12-11 03:12:52.243654,11.388063430786133,3000,64,google.ca
2016-12-11 03:12:52.475366,10.464906692504883,3000,64,google.ca
2016-12-11 03:12:52.706330,8.719921112060547,3000,64,google.ca
2016-12-11 03:12:52.936495,9.361028671264648,3000,64,google.ca
2016-12-11 03:12:53.166322,7.586956024169922,3000,64,google.ca
2016-12-11 03:12:53.394296,7.7381134033203125,3000,64,google.ca
2016-12-11 03:12:53.623198,7.592916488647461,3000,64,google.ca
2016-12-11 03:12:53.852195,8.93092155456543,3000,64,google.ca
2016-12-11 03:12:54.082617,10.549068450927734,3000,64,google.ca
2016-12-11 03:12:54.314621,10.998010635375977,3000,64,google.ca
2016-12-11 03:12:54.547063,11.096000671386719,3000,64,google.ca
2016-12-11 03:12:54.779057,10.461807250976562,3000,64,google.ca
```

---

# TRACEBACK

```
sudo python3 main.py -pf TEST.csv 
Traceback (most recent call last):
  File "main.py", line 78, in <module>
    Plot.PlotFile(parsed.plotfile)
  File "/Users/arianagiroux/Documents/PingStats/Plot.py", line 189, in __init__
    self.ax1.plot_date(x, y)  # TODO `ax1.plot_date` wont accept dates
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/matplotlib/__init__.py", line 1812, in inner
    return func(ax, *args, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/matplotlib/axes/_axes.py", line 1494, in plot_date
    ret = self.plot(x, y, fmt, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/matplotlib/__init__.py", line 1812, in inner
    return func(ax, *args, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/matplotlib/axes/_axes.py", line 1425, in plot
    self.add_line(line)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/matplotlib/axes/_base.py", line 1708, in add_line
    self._update_line_limits(line)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/matplotlib/axes/_base.py", line 1730, in _update_line_limits
    path = line.get_path()
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/matplotlib/lines.py", line 925, in get_path
    self.recache()
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/matplotlib/lines.py", line 612, in recache
    x = np.asarray(xconv, np.float_)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/numpy/core/numeric.py", line 482, in asarray
    return array(a, dtype, copy=False, order=order)
```

---

### tests.py output

```
Sun Dec 11 03:18:06 2016
os.name: posix
platform.system: Darwin
platform.release: 16.1.0
PingStats version: 2.2
Python version (via sys.version): 3.5.1 (v3.5.1:37a07cee5969, Dec  5 2015, 21:12:44) 
[GCC 4.2.1 (Apple Inc. build 5666) (dot 3)]
stdout: 
b'4c5ff38 updated version tag to 2.2\n'
stderr:
b''


.....................
----------------------------------------------------------------------
Ran 21 tests in 1.977s

OK
```

>It should be noted that this commit does not contain tests for `Plot.Plotfile`
